[package]
name = "waybar"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
cairo-rs = "0.18"
wayland-client = "0.31"
wayland-protocols-wlr = { version = "0.2", features = ["client"] }

